### ISSUE TITLE
关于残差

### ISSUE THREAD

**Issue by zest-inno** [Coding-Cow/DVSC#1]
请问为啥我没在代码里里见到论文中相减得到残差的操作

**Comment by hwniu** [comment]
您好，谢谢您的提醒，由于我的代码版本管理问题，将非本篇文章的代码进行了上传，我已经快速将文章对应代码的核心更新上去了，只需要将main文件中from network_model import Video_semantic，改成from network_model_DVC import Video_semantic即可，另外关于原来的那个network_model.py文件，是我当时根据文章《Neural Compression-Based Feature Learning for Video Restoration》做的简单的尝试，但是我当时没有重点关注这个，这个文件应该也是可以run起来的，其借鉴了所提文章的思路，针对旧的network_model.py，结合所提文章可以理解；希望及时的回复可以帮到您

**Comment by code-research-cattle** [comment]
> 请问为啥我没在代码里里见到论文中相减得到残差的操作

您好，谢谢您的提醒，由于我的代码版本管理问题，将非本篇文章的代码进行了上传，我已经快速将文章对应代码的核心更新上去了，只需要将main文件中from network_model import Video_semantic，改成from network_model_DVC import Video_semantic即可，另外关于原来的那个network_model.py文件，是我当时根据文章《Neural Compression-Based Feature Learning for Video Restoration》做的简单的尝试，但是我当时没有重点关注这个，这个文件应该也是可以run起来的，其借鉴了所提文章的思路，针对旧的network_model.py，结合所提文章可以理解；希望及时的回复可以帮到您
